# **Numpy**

In [100]:
import pandas as pd
import numpy as np

# **1️⃣ Creating Arrays**

## Creating Basic Arrays from Lists

In [101]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [102]:
sample_array.dtype

dtype('int64')

In [103]:
sample_array.shape

(3,)

---

# **2️⃣ Array Creation Functions**

## **np.ones()** - Create arrays filled with 1s

In [104]:
# np.ones() = Create an array filled with all 1s

ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [105]:
ones.dtype

dtype('float64')

In [106]:
type(ones)

numpy.ndarray

In [107]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [109]:
ones = np.ones(5, dtype = int)
ones

array([1, 1, 1, 1, 1])

## **np.zeros()** - Create arrays filled with 0s

In [110]:
# np.zeros() = Create an array filled with all 0s
# help(np.zeros)

zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [111]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

## **np.arange()** - Create sequences of numbers

In [112]:
# np.arange() = Create a sequence of numbers (like Python's range, but returns an array)
# help(np.arange)

# Start from 0, go to 10, step by 2
range_array = np.arange(0, 10, 2)  # [0 2 4 6 8]
range_array


array([0, 2, 4, 6, 8])

## **np.random** - Generate random numbers

> A NumPy tool for generating random numbers

In [113]:
# creates random floats between 0 and 1.
random_number = np.random.rand()
random_number


# * np.random.random((3, 4)) does exactly the same thing as np.random.rand(3, 4)
# - creates random floats between 0 and 1.

0.8817242737249168

In [114]:
random_array = np.random.random((5, 3))
random_array

array([[0.79785515, 0.60734465, 0.22847096],
       [0.21669936, 0.81388726, 0.6644221 ],
       [0.35806052, 0.97148125, 0.88976078],
       [0.6715117 , 0.36922971, 0.30875658],
       [0.93938381, 0.44346616, 0.80001715]])

In [115]:
random_array.shape

(5, 3)

In [116]:
random_array.dtype

dtype('float64')

In [117]:
random_array_2 = np.random.rand(5,3)
random_array_2

array([[0.93972208, 0.4920067 , 0.65310841],
       [0.08625533, 0.65258141, 0.21508353],
       [0.67052526, 0.10104555, 0.49520819],
       [0.5210169 , 0.48351939, 0.75672415],
       [0.7545206 , 0.70637785, 0.63163051]])

In [118]:
# np.random.randint()
# generates random whole numbers (integers) within a range you specify.

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 6, 4, 5, 9],
       [2, 6, 9, 4, 6],
       [3, 1, 3, 9, 1]], dtype=int32)

In [119]:
random_array.size

15

In [120]:
random_array.shape

(3, 5)

In [121]:
random_array = np.random.randint(0, 10)
random_array

3

---

## **📋 Quick Reference - Array Creation Functions**

---

# **3️⃣ Random Numbers & Seeding** 🎲

## **Pseudo-random numbers & Seeding**

In [122]:
# Pseudo-random numbers

np.random.seed(42)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [123]:
np.random.seed(42)
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [124]:
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [125]:
random_array_4.shape

(5, 3)

---

# **4️⃣ Viewing & Inspecting Arrays**

## **Finding Unique Values**

In [126]:
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [127]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9], dtype=int32)

In [128]:
np.unique([1,1,1,1,3,4,5,6,2,2,2,7,8,10,11])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [129]:
values, counts = np.unique([1,1,1,1,3,4,5,6,2,2,2,7,8,10,11], return_counts=True)
print(values)
print(counts)

[ 1  2  3  4  5  6  7  8 10 11]
[4 3 1 1 1 1 1 1 1 1]


In [130]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [131]:
a1

array([1, 2, 3, 4, 5])

In [132]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [133]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [134]:
a1[0]

np.int64(1)

In [135]:
a2.shape

(2, 3)

In [136]:
a2[0]

array([1. , 2. , 3.3])

In [137]:
a3.shape

(2, 3, 3)

In [138]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [140]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [141]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4


array([[[[2, 6, 4, 8, 6],
         [1, 3, 8, 1, 9],
         [8, 9, 4, 1, 3],
         [6, 7, 2, 0, 3]],

        [[1, 7, 3, 1, 5],
         [5, 9, 3, 5, 1],
         [9, 1, 9, 3, 7],
         [6, 8, 7, 4, 1]],

        [[4, 7, 9, 8, 8],
         [0, 8, 6, 8, 7],
         [0, 7, 7, 2, 0],
         [7, 2, 2, 0, 4]]],


       [[[9, 6, 9, 8, 6],
         [8, 7, 1, 0, 6],
         [6, 7, 4, 2, 7],
         [5, 2, 0, 2, 4]],

        [[2, 0, 4, 9, 6],
         [6, 8, 9, 9, 2],
         [6, 0, 3, 3, 4],
         [6, 6, 3, 6, 2]],

        [[5, 1, 9, 8, 4],
         [5, 3, 9, 6, 8],
         [6, 0, 0, 8, 8],
         [3, 8, 2, 6, 5]]]], dtype=int32)

In [142]:
a4[1, 2, 1, :4]

array([5, 3, 9, 6], dtype=int32)

In [143]:
a4.shape

(2, 3, 4, 5)

In [144]:
a4.ndim

4

In [145]:
a4.size

120

---

# **5️⃣ Array Operations**

## **Working with Arrays - Key Operations**

## **A. Arithmetic Operations** ➕➖✖️➗

In [146]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [147]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [148]:
# Adding two arrays

a1 + ones

array([2., 3., 4.])

In [149]:
# Subtraction
a1 - ones

array([0., 1., 2.])

In [150]:
# Multiplication
a1 * ones

array([1., 2., 3.])

In [151]:
a1

array([1, 2, 3])

In [152]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [153]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [154]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

---

## **B. Broadcasting Explained** 💡

*This is where NumPy gets intelligent - matching arrays of different shapes!*

### **The Problem: Different Shapes**

#### **Broadcasting Rules** (The Simple Version)

---

## The Rule
Compare shapes from **right to left**.

✅ **Works if:**
- Numbers are the same
- One is `1`
- One is missing

❌ **Fails if:**
- Numbers are different (and neither is `1`)

---

## Examples

### ✅ Works
```python
(3,) + (5, 3)     # Missing → treated as 1
(2, 1) + (2, 3)   # 1 → stretches to 3
2 * (2, 3)        # Scalar works always
```

### ❌ Fails
```python
(2, 3) + (2, 3, 3)  # Can't match
(3,) + (4,)         # 3 ≠ 4
```

---

## Why `a2 * a3` Failed

```python
a2: (2, 3)
a3: (2, 3, 3)

Compare right to left:
   2  3
2  3  3
↑  ↑  ↑
❌ ✅ ✅

# Problem: Extra `2` doesn't match
```

---

## How to Fix

```python
# Add a dimension:
a2[:, :, np.newaxis] * a3  # Now works!
```

---

## Remember
- `*` = element-wise (uses broadcasting)
- `@` = matrix multiply (different!)
- Scalar always works

---

## What "Stretching" Means

**Broadcasting = NumPy automatically copying/repeating small arrays to match big arrays**

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])    # 2 rows, 3 columns

b = np.array([10, 20, 30])   # 1 row, 3 columns

# NumPy copies b to match a's rows:
# b becomes [[10, 20, 30],
#            [10, 20, 30]]

a * b  # Now it works!
# Result: [[10, 40, 90],
#          [40, 100, 180]]
```

- Same size? Just multiply ✅
- One is smaller? Copy it to match ✅  
- Can't figure out how to copy? Error ❌

---

#### **Broadcasting Explained with Real Examples**

##### **Example 1: Missing Dimension** (One array has fewer dimensions)

In [155]:
# Array A: just 3 numbers in a row
A = np.array([1, 2, 3])
print("A =", A)
print("A.shape =", A.shape)  # (3,) ← Only says "3 columns", doesn't say how many rows

# Array B: 5 rows, 3 columns
B = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90],
              [11, 22, 33],
              [44, 55, 66]])
print("\nB =\n", B)
print("B.shape =", B.shape)  # (5, 3) ← Says "5 rows, 3 columns"

# Let's add them!
result = A + B
print("\nA + B =\n", result)

A = [1 2 3]
A.shape = (3,)

B =
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 22 33]
 [44 55 66]]
B.shape = (5, 3)

A + B =
 [[11 22 33]
 [41 52 63]
 [71 82 93]
 [12 24 36]
 [45 57 69]]


### What just happened?

```
A.shape = (3,)    ← "Missing" the rows dimension
B.shape = (5, 3)  ← Has both rows and columns

NumPy says:
"A is missing the first dimension (rows)"
"So I'll treat it like it has 1 row"
"Then I'll copy that 1 row 5 times to match B's 5 rows"

A becomes:  [[1, 2, 3],   ← Copy 1
             [1, 2, 3],   ← Copy 2
             [1, 2, 3],   ← Copy 3
             [1, 2, 3],   ← Copy 4
             [1, 2, 3]]   ← Copy 5

Now add to B!
```

##### **Example 2: Size is 1** (One dimension has size 1)

In [156]:
# Array C: 2 rows, but only 1 column
C = np.array([[10],
              [20]])
print("C =\n", C)
print("C.shape =", C.shape)  # (2, 1) ← 2 rows, 1 column

# Array D: 2 rows, 3 columns
D = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nD =\n", D)
print("D.shape =", D.shape)  # (2, 3) ← 2 rows, 3 columns

# Let's add them!
result = C + D
print("\nC + D =\n", result)

C =
 [[10]
 [20]]
C.shape = (2, 1)

D =
 [[1 2 3]
 [4 5 6]]
D.shape = (2, 3)

C + D =
 [[11 12 13]
 [24 25 26]]


### What just happened?

```
C.shape = (2, 1)  ← 2 rows, 1 column (the "1" is the key!)
D.shape = (2, 3)  ← 2 rows, 3 columns

NumPy says:
"C has only 1 column, but D has 3 columns"
"Since C has 1, I can copy that column 3 times!"

C becomes:  [[10, 10, 10],   ← Copied the 10 three times
             [20, 20, 20]]   ← Copied the 20 three times

Now add to D!
```

**The magic: When a dimension is `1`, NumPy copies it to match the other number!**

##### **Example 3: When It FAILS** (Neither is 1, dimensions don't match)

In [157]:
# Array E: 3 numbers
E = np.array([1, 2, 3])
print("E =", E)
print("E.shape =", E.shape)  # (3,)

# Array F: 4 numbers
F = np.array([10, 20, 30, 40])
print("\nF =", F)
print("F.shape =", F.shape)  # (4,)

# Try to add them... THIS WILL FAIL!
# Uncomment to see the error:
# result = E + F

E = [1 2 3]
E.shape = (3,)

F = [10 20 30 40]
F.shape = (4,)


### Why does it fail?

```
E.shape = (3,)
F.shape = (4,)

NumPy says:
"E has 3 elements, F has 4 elements"
"3 ≠ 4, and neither is 1"
"I don't know how to copy 3 to make 4, or 4 to make 3"
"ERROR!"
```

**The rule: If numbers are different AND neither is 1, NumPy gives up!**

---

## 🎯 THE SIMPLE RULE

When comparing two dimensions:

| Situation | NumPy says | Example |
|-----------|------------|---------|
| **Same number** | ✅ Perfect! Just use them | `(3,) + (3,)` |
| **One is 1** | ✅ Copy the 1 to match the other | `(2, 1) + (2, 3)` → Copy 1→3 |
| **One is missing** | ✅ Treat missing as 1, then copy | `(3,) + (5, 3)` → Add 1, then copy |
| **Different (neither is 1)** | ❌ ERROR! Can't match | `(3,) + (4,)` → FAIL |

---

### Think of it like this:

- ✅ **Same** = Already match, no problem
- ✅ **1** = NumPy can copy it
- ✅ **Missing** = Treat as 1, then copy
- ❌ **Different (not 1)** = NumPy doesn't know what to do

In [158]:
a1

array([1, 2, 3])

In [159]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [160]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [161]:
# Since a2 * a3 is not working
# how we can make it work 

# Solution:
# Using np.newaxis()

In [162]:
# np.newaxis
# -> adds a new dimension to your array.
# Think of it like adding a new layer of brackets [ ] to your array.


a1, a1.shape

(array([1, 2, 3]), (3,))

In [163]:
# Example 1: 1D → 2D (Add a row dimension)
c = a1[np.newaxis,:]
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


In [164]:
a1 ,a1.shape

(array([1, 2, 3]), (3,))

In [165]:

# Example 2: 1D → 2D (Add a column dimension)
d = a1[:, np.newaxis]
print(d)
print(d.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [166]:
# Now back to a2 * a3

print(f"Array a2: \n{a2}")
print(f"Shape a2: {a2.shape}")
print()

print(f"Array a3: \n{a3}")
print(f"Shape a2: {a3.shape}")
print()

print(f"{a2.shape} vs {a3.shape}")
print("or")
print(f"{a2.shape}\n{a3.shape}")

Array a2: 
[[1.  2.  3.3]
 [4.  5.  6.5]]
Shape a2: (2, 3)

Array a3: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Shape a2: (2, 3, 3)

(2, 3) vs (2, 3, 3)
or
(2, 3)
(2, 3, 3)


In [167]:
# Attempting a2*a3

print(a2[np.newaxis, :, :])
a2[np.newaxis, :, :].shape

[[[1.  2.  3.3]
  [4.  5.  6.5]]]


[[[1.  2.  3.3]
  [4.  5.  6.5]]]


(1, 2, 3)

In [168]:
# Still not work??
# a2[np.newaxis, :, :] * a3

---

## **C. Using np.newaxis for Broadcasting** ✨

### **How to Add Dimensions Correctly**

In [169]:
# ❌ WRONG: Adding dimension at the START
print("a2 shape:", a2.shape)  # (2, 3)
wrong = a2[np.newaxis, :, :]
print("a2[np.newaxis, :, :] shape:", wrong.shape)  # (1, 2, 3)

print("\nComparing with a3:")
print(f"{wrong.shape} vs {a3.shape}")
print("    1  2  3")
print("    2  3  3")
print("    ↑  ↑  ↑")
print("    ✅ ❌ ✅  <- FAILS at position 2 (2 ≠ 3)")

# This will ERROR:
# wrong * a3

a2 shape: (2, 3)
a2[np.newaxis, :, :] shape: (1, 2, 3)

Comparing with a3:
(1, 2, 3) vs (2, 3, 3)
    1  2  3
    2  3  3
    ↑  ↑  ↑
    ✅ ❌ ✅  <- FAILS at position 2 (2 ≠ 3)


In [170]:
# ✅ CORRECT: Adding dimension at the END
print("a2 shape:", a2.shape)  # (2, 3)
correct = a2[:, :, np.newaxis]
print("a2[:, :, np.newaxis] shape:", correct.shape)  # (2, 3, 1)

print("\nComparing with a3:")
print(f"{correct.shape} vs {a3.shape}")
print("    2  3  1")
print("    2  3  3")
print("    ↑  ↑  ↑")
print("    ✅ ✅ ✅  <- ALL MATCH! (1 broadcasts to 3)")

# This will WORK:
result = correct * a3
print("\nResult shape:", result.shape)
print("✅ Success! It worked!")

a2 shape: (2, 3)
a2[:, :, np.newaxis] shape: (2, 3, 1)

Comparing with a3:
(2, 3, 1) vs (2, 3, 3)
    2  3  1
    2  3  3
    ↑  ↑  ↑
    ✅ ✅ ✅  <- ALL MATCH! (1 broadcasts to 3)

Result shape: (2, 3, 3)
✅ Success! It worked!


### 🎯 The Rule for np.newaxis

When you need to add a dimension for broadcasting:

1. **Look at the shapes** and compare **right to left**
2. **Find WHERE they don't match**
3. **Add dimension** to turn the mismatched number into `1`

#### Example:
```
a2: (2, 3)      - Missing a dimension on the right
a3: (2, 3, 3)   - Has all three dimensions

Need to add dimension at the END:
a2[:, :, np.newaxis] → (2, 3, 1)
```

#### Another way to think about it:

- `np.newaxis` at **beginning** `[np.newaxis, :, :]` = Add rows
- `np.newaxis` at **end** `[:, :, np.newaxis]` = Add depth/layers
- `np.newaxis` in **middle** `[:, np.newaxis, :]` = Add columns

**You needed to add depth (a third dimension), so you put it at the end!**

In [171]:
# Last try a2 * a3

a2[:, :, np.newaxis] * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [172]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

---

## **D. Advanced Arithmetic Operations** 🔬

In [173]:
# Divison

a1 / ones

array([1., 2., 3.])

### **Division Operations**

In [174]:
a1, a1.shape, a2, a2.shape
# a1 / a2

(array([1, 2, 3]),
 (3,),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [175]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [176]:
a1 / a2

array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [177]:
# Floor division (//)
# -> divides and rounds DOWN to the nearest whole number.
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

---

### **Floor Division & Modulo (Remainder)**

In [178]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [179]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

---

### **Power & Square Operations**

In [180]:
# Power

a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [181]:
# or we can use 
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [182]:
a1 + ones

array([2., 3., 4.])

In [183]:
np.add(a1, ones)

array([2., 3., 4.])

In [184]:
# Modulo (%)
# Modulo gives you the REMAINDER after division.

a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

---

### **Modulo (Remainder) Operation**

In [185]:
# or

np.mod(a2, 2)

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [186]:
# np.exe - Exponential Function
'''
- np.exp(x) calculates e raised to the power x (e^x)
-> Where e ≈ 2.71828 (Euler's number)
'''

np.exp(a1)


array([ 2.71828183,  7.3890561 , 20.08553692])

---

### **Exponential & Logarithmic Functions** 📈

In [187]:
# np.log() - Natural Logarithm
# np.log(x) calculates the natural logarithm of x (log base e)
# -> It's the OPPOSITE of np.exp()

np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### ***Aggregation***

- `Aggregation` = Taking an array and summarizing it into a single value (or smaller values).
- Performing the same operation on a number of things
- **Think of it as:** "Give me one number that describes this whole array"

In [188]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [189]:
sum(listy_list)

6

In [190]:
# Array (main thing)
a1

array([1, 2, 3])

In [191]:
type(a1)

numpy.ndarray

In [192]:
# NumPy array method called on array directly
a1.sum()

np.int64(6)

In [193]:
# Python built-in function
sum(a1)

np.int64(6)

In [194]:
# NumPy function
np.sum(a1)

# More options/control

np.int64(6)

In [201]:
# Creative a massive NumPy array

massive_array = np.random.random(100000)
massive_array

100000

In [205]:
massive_array

array([0.76233589, 0.97731506, 0.63094364, ..., 0.77659378, 0.14019329,
       0.75455037], shape=(100000,))

In [ ]:
# %timeit  # How long a lines takes to run 

%timeit sum(massive_array)
%timeit np.sum(massive_array)
%timeit massive_array.sum() 

7.9 ms ± 530 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
34.8 μs ± 1.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
32.2 μs ± 1.79 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [207]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
# Average of all elements

np.mean(a2)

np.float64(3.6333333333333333)

In [ ]:
# maximum / Largest element

np.max(a2)

np.float64(6.5)

In [ ]:
# minimum / Smallest element

np.min(a2)

np.float64(1.0)

**median** 

> The middle value when you sort all numbers from smallest to largest

**How to compute**
- Sort the numbers.
- If count is `odd` → pick the middle.
- If count is `even` → average the two middle values.


In [212]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:

np.median(a2)

np.float64(3.65)

**Variance**

> How spread out the numbers are from the average

**Formula**: `Average of squared differences from the mean`


- Low variance = Numbers are close together
- High variance = Numbers are scattered far apart



In [216]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [214]:
np.var(a2)

np.float64(3.3222222222222224)

**Standard Deviation**

> The square root of variance. It's variance in the original units.

**Formula:** `√variance`


**Why it matters**
- It brings the measure of spread back into the same units as the data.
- Easier to interpret: “On average, data points are about 5 units away from the mean.”

**Example** 
- Variance = 2.67
- Standard deviation = √2.67 ≈ 1.63


> So the data values are typically about 1.63 units away from the mean.

In [217]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [213]:
np.std(a2)

np.float64(1.8226964152656422)

In [ ]:
3.3222222222222224 ** 0.5  # Square root

1.8226964152656422

In [218]:
# or

np.sqrt(np.var(a2))

np.float64(1.8226964152656422)

In [219]:
np.std(a2) == np.sqrt(np.var(a2))

np.True_