# **NumPy**

In [1]:
import numpy as np


In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

a3 = np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ***Reshaping and Transposing***

#### **What is Reshape?**
Reshape changes the shape of an array. The data stays the same, but the layout changes. For example, change 6 numbers in a line to 2 rows and 3 columns.

**Why use Reshape?**
- Make arrays same size to do math together
- Get data in right format for models
- Rearrange without losing data

#### **What is Transpose?**
Transpose flips an array. Rows become columns, columns become rows. Use `.T` to do it.

**Why use Transpose?**
- Flip data from rows to columns
- Get data ready for calculations
- Fix array shape when needed

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a2.shape

(2, 3)

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# a2 * a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
# Reshaping

a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [13]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [16]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [17]:
# np.newline -> learn difference

In [18]:
a2 , a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [19]:
# Transpose

a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [20]:
a2.T.shape

(3, 2)

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

### **Dot product**

- [Learn More](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

---

**How to multiply matrix**

>- |   - - -
>- |
>- |


**Use:**
- a@b
- np.dot(a, b)


In [29]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))

mat2 = np.random.randint(10, size=(5, 3))


In [30]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [31]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [32]:
mat1.shape , mat2.shape

((5, 3), (5, 3))

In [33]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [35]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [38]:
# Element-wise multiplication (Hadamard product)
# not dot product 
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [ ]:
# This will fail as the inner dimensions of the matrices do not match
np.dot(mat1, mat1)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

---

## **Element-Wise Multiplication vs Dot Product**

### **Example: Two Small Matrices**

```
mat1 = [1  2]      mat2 = [3  4]
       [5  6]             [7  8]
```

---

### **1️⃣ ELEMENT-WISE MULTIPLICATION (Hadamard Product)**
**Use:** `mat1 * mat2`

Multiply matching positions, one by one:

```
[1  2]   *   [3  4]   =   [1×3  2×4]   =   [3   8]
[5  6]       [7  8]       [5×7  6×8]       [35  48]
```

**Result shape:** Same as input `(2, 2)`

---

### **2️⃣ DOT PRODUCT (Matrix Multiplication)**
**Use:** `mat1 @ mat2` or `np.dot(mat1, mat2)`

**RULE:** `(rows1, cols1) @ (rows2, cols2)` → `(rows1, cols2)`

**Constraint:** `cols1 must equal rows2`

For dot product: Multiply rows of mat1 by columns of mat2, then sum:

```
mat1 shape = (2, 2)
mat2 shape = (2, 2)  ✅ Can multiply! (2 == 2)

Result = [1×3 + 2×7,    1×4 + 2×8]   =   [17  20]
         [5×3 + 6×7,    5×4 + 6×8]       [57  68]
```

**Result shape:** `(2, 2)` (rows of mat1, cols of mat2)

---

### **Key Difference**

| Operation | Symbol | Formula | Result |
|-----------|--------|---------|--------|
| **Element-Wise** | `*` | Position by position | Same shape |
| **Dot Product** | `@` | Rows × Columns (sum) | (rows1, cols2) |

**Element-wise:** `[3, 8, 35, 48]` (just multiply)  
**Dot product:** `[17, 20, 57, 68]` (multiply + sum)

In [ ]:
# Since dim1 of mat1 == dim0 of ma2

mat_trans = np.transpose(mat2)

In [44]:
# Dot prdoct

np.dot(mat1, mat_trans)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [45]:
mat1@mat_trans

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)