# **Numpy**

In [153]:
import pandas as pd
import numpy as np

# ***Creating arrays***

In [154]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [155]:
sample_array.dtype

dtype('int64')

In [156]:
sample_array.shape

(3,)


#### **np.ones()**

In [157]:
# np.ones() = Create an array filled with all 1s

ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [158]:
ones.dtype

dtype('float64')

In [159]:
type(ones)

numpy.ndarray

In [160]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [161]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [162]:
ones = np.ones(5, dtype = int)
ones

array([1, 1, 1, 1, 1])

#### **np.zeros()**

In [163]:
# np.zeros() = Create an array filled with all 0s
# help(np.zeros)

zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [164]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

#### **np.arange()**

In [165]:
# np.arange() = Create a sequence of numbers (like Python's range, but returns an array)
# help(np.arange)

# Start from 0, go to 10, step by 2
range_array = np.arange(0, 10, 2)  # [0 2 4 6 8]
range_array


array([0, 2, 4, 6, 8])

#### **np.random**

> A NumPy tool for generating random numbers

- It's a submodule (a toolbox within NumPy) that creates random data for you.



In [166]:
# creates random floats between 0 and 1.
random_number = np.random.rand()
random_number


# * np.random.random((3, 4)) does exactly the same thing as np.random.rand(3, 4)
# - creates random floats between 0 and 1.

0.9568008851264563

In [167]:
random_array = np.random.random((5, 3))
random_array

array([[0.6767699 , 0.48252095, 0.49302566],
       [0.08328441, 0.09170415, 0.60244093],
       [0.55370305, 0.2127279 , 0.94619454],
       [0.78129605, 0.1134646 , 0.93092911],
       [0.97424821, 0.99593124, 0.05587115]])

In [168]:
random_array.shape

(5, 3)

In [169]:
random_array.dtype

dtype('float64')

In [170]:
random_array_2 = np.random.rand(5,3)
random_array_2

array([[0.73703556, 0.54591577, 0.70583148],
       [0.96865194, 0.68803001, 0.83696387],
       [0.86686871, 0.83848076, 0.42609148],
       [0.22257642, 0.3966516 , 0.89189691],
       [0.14660482, 0.51332617, 0.23322807]])

In [171]:
# np.random.randint()
# generates random whole numbers (integers) within a range you specify.

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 0, 5, 3, 0],
       [6, 8, 3, 3, 5],
       [2, 5, 6, 9, 9]], dtype=int32)

In [172]:
random_array.size

15

In [173]:
random_array.shape

(3, 5)

In [174]:
random_array = np.random.randint(0, 10)
random_array

2

## **Similar Functions: Array Creation** 🛠️

### **Quick Reference - All Ways to Create Arrays (Without Lists!)**

| Function | Creates | Use Case | Example |
|----------|---------|----------|---------|
| `np.zeros()` | All **0s** | Initialize empty arrays | `np.zeros((3, 3))` |
| `np.ones()` | All **1s** | Start with baseline values | `np.ones((3, 3))` |
| `np.full()` | All **same value** | Custom initialization | `np.full((3, 3), 7)` |
| `np.arange()` | **Range** of numbers | Sequential data | `np.arange(10)` → 0-9 |
| `np.linspace()` | **Evenly spaced** numbers | Precise ranges | `np.linspace(0, 1, 5)` |

---

### **When to Use Each:**

**`np.zeros()`** ← Start with blank slate
```python
# Reserve space for results you'll fill later
results = np.zeros((100, 10))
```

**`np.ones()`** ← Start with 1s everywhere
```python
# Initialize weights/masks
weights = np.ones((50, 50))
```

**`np.full()`** ← Custom starting value
```python
# Fill with a specific number
matrix = np.full((5, 5), 99)
```

**`np.arange()`** ← Like Python's range() but creates array
```python
# Create sequence 0 to 9
numbers = np.arange(10)
```

**`np.linspace()`** ← Exact number of points
```python
# 5 points evenly from 0 to 1
points = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1.  ]
```

---

### **Pro Tip** 💡

All these functions let you **specify shape** without nested lists:

```python
# ❌ Tedious
big_array = np.array([[0, 0, 0, ...], ...])

# ✅ Clean
big_array = np.zeros((1000, 1000))  # Much easier!
```

---

### **Key Difference: `arange()` vs `linspace()`**

| Function | You specify | Step size |
|----------|------------|-----------|
| `arange(0, 10, 2)` | **Start, stop, step** | You control the step (2) |
| `linspace(0, 10, 5)` | **Start, stop, count** | NumPy calculates the step |

```python
# arange: Step by 2
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# linspace: 5 points from 0 to 10
np.linspace(0, 10, 5)  # [0. , 2.5, 5. , 7.5, 10.]
```

## **Pseudo-random numbers & Seeding** 🎲

### **What is `np.random.seed()`?**

A function that sets the **starting point** for NumPy's random number generator.

---

### **Key Concept: Pseudo-Random Numbers**

Computers can't create truly random numbers - they use a **mathematical formula**:

```
Seed (starting number) → Formula → Chain of "random" numbers
```

**Same seed = Same sequence of "random" numbers**

---

### **What Happens Without a Seed?** ⏰

When you **don't set a seed**, NumPy uses the **current time** (down to microseconds) as the seed:

```python
# No seed provided
np.random.randint(0, 10, size=5)
# Behind the scenes: seed = current time (e.g., 1708185722.456123)
# Output: [3, 7, 2, 9, 1]

# Run again a moment later
np.random.randint(0, 10, size=5)
# Behind the scenes: seed = new time (e.g., 1708185722.789456)
# Output: [5, 8, 4, 1, 6]  ← Different time = different seed!
```

**This creates the illusion of randomness!** 🎭

Since the current time is always changing, you get different numbers each time - making it **appear** truly random (even though it's still following the formula).

---

### **Why Use a Seed?** 🎯

✅ **Reproducibility** - Get same "random" numbers every time  
✅ **Debugging** - Test with consistent data  
✅ **Collaboration** - Share results teammates can reproduce  
✅ **Scientific experiments** - Required for valid research

---

### **Examples**

#### **Without Seed (Different Every Time)**
```python
np.random.randint(0, 10, size=5)
# Run 1: [3, 7, 2, 9, 1]
# Run 2: [5, 8, 4, 1, 6]  ← Different!
# Run 3: [2, 3, 9, 7, 4]  ← Different again!

# Why? Current time keeps changing → different seed each time!
```

#### **With Seed (Same Every Time)**
```python
np.random.seed(42)
np.random.randint(0, 10, size=5)
# Always: [6, 3, 7, 4, 6]

np.random.seed(42)
np.random.randint(0, 10, size=5)
# Always: [6, 3, 7, 4, 6]  ← Identical!

# Why? Seed 42 always starts the formula at the same point!
```

---

### **Best Practices** 💡

```python
# ✅ Set seed ONCE at the top of your notebook
import numpy as np
np.random.seed(42)  # Any number works (42 is popular!)

# Now all random operations are reproducible
data1 = np.random.rand(100)
data2 = np.random.randint(0, 50, size=20)

# ❌ Don't reset seed repeatedly (makes everything identical)
np.random.seed(42)
a = np.random.rand(5)
np.random.seed(42)  # Don't do this!
b = np.random.rand(5)  # Now b = a (not desired!)
```

---

### **Quick Analogy** 🎮

**No Seed** = Valorant match (enemies spawn randomly each round)  
**With Seed** = Practice range (enemies in same spots for practice)

---

### **Common Seed Numbers**

- `42` - Most popular (from "Hitchhiker's Guide to the Galaxy")
- `0` - Simple, common choice
- `123` - Easy to remember
- Any integer works - just pick one and stick with it!

---

### **When to Remove Seed**

```python
# During development/testing: USE seed
np.random.seed(42)
test_data = np.random.rand(100)

# In production/final analysis: REMOVE seed for true randomness
# np.random.seed(42)  ← Comment out
real_data = np.random.rand(100)
```

In [175]:
# Pseudo-random numbers

np.random.seed(42)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [176]:
np.random.seed(42)
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [177]:
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [178]:
random_array_4.shape

(5, 3)

## **Viewing arrays and matrices**

- `np.unique()` is a function that finds and returns only the unique (non-duplicate) values from an array.

> **Think of it like:** "Show me each item only once, even if it appears multiple times"

In [179]:
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [180]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9], dtype=int32)

In [181]:
np.unique([1,1,1,1,3,4,5,6,2,2,2,7,8,10,11])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [182]:
values, counts = np.unique([1,1,1,1,3,4,5,6,2,2,2,7,8,10,11], return_counts=True)
print(values)
print(counts)

[ 1  2  3  4  5  6  7  8 10 11]
[4 3 1 1 1 1 1 1 1 1]


In [183]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [184]:
a1

array([1, 2, 3, 4, 5])

In [185]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [186]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [187]:
a1[0]

np.int64(1)

In [188]:
a2.shape

(2, 3)

In [189]:
a2[0]

array([1. , 2. , 3.3])

In [190]:
a3.shape

(2, 3, 3)

In [191]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [193]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [201]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4


array([[[[6, 2, 0, 0, 2],
         [5, 6, 5, 5, 5],
         [2, 5, 7, 1, 4],
         [0, 0, 4, 2, 3]],

        [[2, 0, 0, 4, 5],
         [2, 8, 4, 7, 0],
         [4, 2, 0, 3, 4],
         [6, 0, 2, 1, 8]],

        [[9, 5, 9, 2, 7],
         [7, 1, 5, 6, 1],
         [9, 1, 9, 0, 7],
         [0, 8, 5, 6, 9]]],


       [[[6, 9, 2, 1, 8],
         [7, 9, 6, 8, 3],
         [3, 0, 7, 2, 6],
         [1, 1, 6, 5, 2]],

        [[8, 9, 5, 9, 9],
         [5, 0, 3, 9, 5],
         [5, 4, 0, 7, 4],
         [4, 6, 3, 5, 3]],

        [[2, 6, 7, 3, 1],
         [9, 2, 0, 7, 2],
         [9, 6, 9, 4, 9],
         [4, 6, 8, 4, 0]]]], dtype=int32)

In [205]:
# Get the first 4 numbers of the inner most arrays
a4[1, 2, 1, :4]

array([9, 2, 0, 7], dtype=int32)

In [196]:
a4.shape

(2, 3, 4, 5)

In [197]:
a4.ndim

4

In [198]:
a4.size

120