# **NumPy**

NumPy is a Python library that makes working with numbers and data really fast and easy. Think of it as a superpower for math and data.

#### `NumPy` = "Numerical Python"

**Breaking it down:**

- `Numerical` = dealing with numbers (math, calculations, data)
- `Python` = the programming language it's written for

- **So it literally means:** a Python tool for doing numerical work fast and easily.



![Steps to ML](..\assets\images\numpy-6-step-ml-framework-tools-numpy-highlight.png)

### **The Analogy**
Imagine you have a list of 1 million student test scores. If you use regular Python, doing math on all of them would be slow. NumPy does the same math 50–100x faster because it's built differently under the hood.

### **What does NumPy give you?**
- `Arrays` — Like organized containers for numbers (think: spreadsheet columns, but faster)
- `Math operations` — Add, multiply, filter thousands of numbers in one line
- `Tools for data science` — Functions for statistics, linear algebra, random data, etc.

### **Real world example**

In [65]:
# Without NumPy (slow)
scores = [85, 92, 78, 88, 95]
average = sum(scores) / len(scores)
print(average)

# With NumPy (fast + clean)
import numpy as np
scores = np.array([85, 92, 78, 88, 95])
average = scores.mean()  # One line!
print(average)

87.6
87.6


## **Why Use NumPy?**

### **1. Speed** ⚡ (The biggest reason)

NumPy is **50–100x faster** than regular Python lists for math operations.

```python
# Regular Python - SLOW
numbers = [1, 2, 3, 4, 5]
doubled = [x * 2 for x in numbers]  # Loops through each item

# NumPy - FAST
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
doubled = numbers * 2  # Does all at once!
```

> **Why it's faster:** NumPy uses optimized C code under the hood, while Python lists are slower.

---

### **2. Convenience** 🎯 (Less code, cleaner)

You can do complex math in **one line** instead of writing loops.

```python
# Without NumPy - messy
total = 0
for score in [85, 92, 78]:
    total += score
average = total / 3

# With NumPy - clean
import numpy as np
average = np.array([85, 92, 78]).mean()
```

---

### **3. Foundation for Everything in Data Science** 🏗️

Every major library **depends on NumPy:**

| Library | Purpose | Relationship |
|---------|---------|--------------|
| **Pandas** | Data analysis | Built on NumPy |
| **Scikit-learn** | Machine learning | Uses NumPy arrays |
| **TensorFlow/PyTorch** | Deep learning | Work with NumPy |
| **Matplotlib** | Plotting | Accepts NumPy arrays |


> **Translation:** If you don't know NumPy, you can't effectively use the other tools.

---

### **4. Real-World Necessity** 📊

When dealing with actual datasets:

| Dataset Size | Python List | NumPy |
|--------------|-------------|-------|
| **Small** (100 rows) | ✅ Fine | ✅ Better |
| **Real** (10,000+ rows) | ⚠️ Slow | ✅ Essential |
| **Big** (millions of rows) | ❌ Too slow | ✅ Mandatory |

---

### **5. Built-In Math & Statistics** 🧮

NumPy has hundreds of ready-made functions:

```python
import numpy as np
data = np.array([10, 20, 30, 40, 50])

data.mean()      # Average: 30.0
data.std()       # Standard deviation
data.max()       # Maximum value: 50
data.sum()       # Add everything: 150
np.sqrt(data)    # Square root of each number
```

---

### **Summary: Why NumPy Matters**

| Reason | Benefit |
|--------|---------|
| ⚡ **Speed** | 50–100x faster than normal Python |
| 🎯 **Simplicity** | Write less code, get more done |
| 🏗️ **Necessity** | Every data/ML tool needs it |

## **Python List vs NumPy Array** 🔍

### **They look similar, but they're VERY different!**

---

### **Quick Comparison Table**

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| **Speed** | Slow ❌ | Fast ✅ |
| **Data types** | Can mix (numbers, text, etc.) | Must be same type |
| **Math operations** | Need loops | Direct operations |
| **Memory** | Uses more | Efficient |
| **Purpose** | General storage | Math & data science |

---

### **Key Differences Explained**

#### **1. Math Operations**

**Python List:**
```python
# Lists need loops for math
numbers = [1, 2, 3, 4, 5]
# numbers * 2  # ❌ This doesn't work!
doubled = [x * 2 for x in numbers]  # Need a loop
print(doubled)  # [2, 4, 6, 8, 10]
```

**NumPy Array:**
```python
# Arrays do math directly
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
doubled = numbers * 2  # ✅ Works automatically!
print(doubled)  # [2 4 6 8 10]
```

---

#### **2. Data Types**

**Python List:**
```python
# Lists can mix types
mixed = [1, "hello", 3.14, True]  # ✅ Allowed
print(mixed)  # [1, 'hello', 3.14, True]
```

**NumPy Array:**
```python
# Arrays force one type
import numpy as np
mixed = np.array([1, "hello", 3.14, True])
print(mixed)  # ['1' 'hello' '3.14' 'True'] - all converted to text!
```

> **Why?** NumPy needs **same types** for speed. When you mix, it converts everything to a common type.

---

#### **3. Speed Example**

In [66]:
import numpy as np
import time

# Create a big list and array
size = 1000000
py_list = list(range(size))
np_array = np.array(py_list)

# ===== TIME: Python List =====
start = time.time()
doubled_list = [x * 2 for x in py_list]
list_time = time.time() - start

# ===== TIME: NumPy Array =====
start = time.time()
doubled_array = np_array * 2
array_time = time.time() - start

print(f"Python List time: {list_time:.4f} seconds")
print(f"NumPy Array time: {array_time:.4f} seconds")
print(f"NumPy is {list_time/array_time:.1f}x FASTER! 🚀")

Python List time: 0.1082 seconds
NumPy Array time: 0.0041 seconds
NumPy is 26.6x FASTER! 🚀


---

#### **4. When to Use Each**

**Use Python Lists when:**
- ✅ You have mixed data types (numbers, text, etc.)
- ✅ You're storing general data (not doing math)
- ✅ You need to add/remove items frequently
- ✅ Small dataset (less than 100 items)

**Use NumPy Arrays when:**
- ✅ Doing math or statistics
- ✅ All data is the same type (all numbers)
- ✅ Working with large datasets
- ✅ Need speed for calculations
- ✅ Preparing data for machine learning

---

### **Visual Analogy**

Think of it like transportation:

| Python List | NumPy Array |
|-------------|-------------|
| 🚗 **Car** — Flexible, can carry different things, goes anywhere | 🚄 **Bullet Train** — Super fast, but only on specific tracks, everyone must follow same rules |

---

### **The Bottom Line**

```python
# List = Flexible but slow for math
my_list = [1, 2, 3, 4, 5]  
result = [x * 2 for x in my_list]  # Need a loop

# Array = Strict but fast for math
my_array = np.array([1, 2, 3, 4, 5])  
result = my_array * 2  # Direct operation
```

> **Rule of thumb:** If you're doing **math/data science** → use **NumPy arrays**. For everything else → Python lists are fine.

---

### **Quick Check** ✅

**Question:** If you have 10,000 student exam scores and need to calculate the average, which should you use?

<details>
<summary>Click to see answer</summary>

**NumPy Array!** 

Why? Because:
1. All data is the same type (numbers)
2. You're doing math (calculating average)
3. Large dataset (10,000 items)
4. Speed matters

```python
import numpy as np
scores = np.array([...10000 scores...])
average = scores.mean()  # Fast and clean!
```
</details>

In [67]:
import numpy as np

# Create an ndarray
my_array = np.array([1.5, 2.7, 3.3])

# The STRUCTURE (ndarray)
type(my_array)  # numpy.ndarray

# The DATA TYPE (dtype) inside that array
my_array.dtype  # float64

dtype('float64')

# **NumPy in action**

In [68]:
# Importing the numpy

import numpy as np

### **What is `ndarray`?** 📦

**`ndarray`** = **N-Dimensional Array** (the main NumPy data structure)

Think of it as:
- **1D array** → A single row (like a list)
- **2D array** → A table (rows and columns)
- **3D array** → Multiple tables stacked (like Excel sheets)

```python
import numpy as np

# 1D array (1 dimension)
array_1d = np.array([1, 2, 3, 4, 5])

# 2D array (2 dimensions - rows & columns)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# 3D array (3 dimensions)
array_3d = np.array([[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]])
```

---

## **NumPy Data Types (dtypes)** 🔢

NumPy has **specific data types** to store numbers efficiently. The main ones you'll use:

| Data Type | Code | Description | Example |
|-----------|------|-------------|---------|
| **Integer** | `int64`, `int32` | Whole numbers | `1, 2, 100, -5` |
| **Float** | `float64`, `float32` | Decimal numbers | `3.14, -0.5, 2.0` |
| **Boolean** | `bool` | True/False | `True, False` |
| **String** | `str`, `U10` | Text | `'hello', 'world'` |
| **Complex** | `complex128` | Complex numbers | `1+2j` |

> **The number** (like `64` or `32`) tells you how much memory each item uses. Bigger = more precision, more memory.

**Why does dtype matter?**
- **Speed**: Using the right type makes calculations faster
- **Memory**: Smaller types use less RAM (important for big data)
- **Accuracy**: Floats for decimals, ints for whole numbers

In [69]:
# NumPy's main datatype is ndarray


## 1-D Array / Vector

a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [70]:
type(a1)

numpy.ndarray

In [71]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [72]:
# 2-D Array / matrix
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
# 3-D Array / matrix
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## **Understanding Shape Attribute** 📐

### **Why does `a1` have shape `(5,)` and not `(5, 1)`?**

- `a1 = [1, 2, 3, 4, 5]` is **1D** → only one dimension
- Shape `(5,)` means: "5 elements in a line"
- The comma is needed because it's a Python tuple with one element

**Shape tells you the size along EACH dimension:**

| Array | Dimensions | Shape | Meaning |
|-------|-----------|-------|---------|
| `a1` | 1D | `(5,)` | Just 5 elements in a line |
| `a2` | 2D | `(2, 3)` | 2 rows × 3 columns |
| `a3` | 3D | `(2, 3, 3)` | 2 layers × 3 rows × 3 columns |

---

### **How to Read Shape: Rows and Columns**

For **2D arrays** (like a2):
```
Shape: (2, 3)
       ↓  ↓
    ROWS  COLUMNS

Visual:
     Col 0  Col 1  Col 2
Row 0:  1     2.0    3.3
Row 1:  4     5      6.5
```

**ALWAYS:** First number = **rows** (horizontal), Second = **columns** (vertical)

---

### **Shape for 3D: Layers, Rows, Columns**

```
Shape: (2, 3, 3)
       ↓  ↓  ↓
    LAYERS, ROWS, COLUMNS

Think: 2 stacked tables, each 3×3
```

---

### **Axes Language (Professional way)**

NumPy calls dimensions **"axes"**:
- **Axis 0** = vertical (down) = rows
- **Axis 1** = horizontal (right) = columns  
- **Axis 2** = depth (layers)

So shape `(2, 3)` means:
- Axis 0: size 2
- Axis 1: size 3

---

### **Quick Rule** 🎯

✓ Read shape **left to right**  
✓ First = outermost dimension  
✓ Last = innermost dimension  
✓ For 2D: `(rows, columns)` like a spreadsheet

In [1]:
# Practical demo: Check shapes of a1, a2, a3_
import numpy as np

print("=" * 60)
print("SHAPE DEMO")
print("=" * 60)

# 1D Array
a1 = np.array([1, 2, 3, 4, 5])
print(f"\na1 = {a1}")
print(f"Shape: {a1.shape}")
print(f"  → 1D array with 5 elements")
print(f"  → Read as: 5 elements in a line")

# 2D Array
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
print(f"\na2 = \n{a2}")
print(f"Shape: {a2.shape}")
print(f"  → 2D array with {a2.shape[0]} rows and {a2.shape[1]} columns")
print(f"  → Read as: (rows, columns) = (2, 3)")

# 3D Array
a3_ = np.array([[[1, 2], [3, 4], [5, 6]],
               [[7, 8], [9, 10], [11, 12]]])
print(f"\na3 = \n{a3_}")
print(f"Shape: {a3_.shape}")
print(f"  → 3D array with {a3_.shape[0]} layers, {a3_.shape[1]} rows, {a3_.shape[2]} columns")
print(f"  → Read as: (layers, rows, columns) = (2, 3, 2)")

print("\n" + "=" * 60)
print("ACCESSING SHAPE VALUES")
print("=" * 60)

# You can access individual dimensions
print(f"\na2.shape[0] = {a2.shape[0]}  (number of rows)")
print(f"a2.shape[1] = {a2.shape[1]}  (number of columns)")
print(f"\na3.shape[0] = {a3_.shape[0]}  (number of layers)")
print(f"a3_.shape[1] = {a3_.shape[1]}  (rows per layer)")
print(f"a3_.shape[2] = {a3_.shape[2]}  (columns per row)")

SHAPE DEMO

a1 = [1 2 3 4 5]
Shape: (5,)
  → 1D array with 5 elements
  → Read as: 5 elements in a line

a2 = 
[[1.  2.  3.3]
 [4.  5.  6.5]]
Shape: (2, 3)
  → 2D array with 2 rows and 3 columns
  → Read as: (rows, columns) = (2, 3)

a3 = 
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)
  → 3D array with 2 layers, 3 rows, 2 columns
  → Read as: (layers, rows, columns) = (2, 3, 2)

ACCESSING SHAPE VALUES

a2.shape[0] = 2  (number of rows)
a2.shape[1] = 3  (number of columns)

a3.shape[0] = 2  (number of layers)
a3_.shape[1] = 3  (rows per layer)
a3_.shape[2] = 2  (columns per row)


## **Shape + Axes Concept** 🎯

### **Axes explained:**

**Axis = dimension number (0, 1, 2, ...)**

For `a2` with shape `(2, 3)`:
```
axis 0 (vertical/rows)   ↓
axis 1 (horizontal/cols) →

a2 = [[1  2.0  3.3]      ← Axis 0, position 0
      [4  5    6.5]]     ← Axis 0, position 1
```

| Axis | Direction | Size |
|------|-----------|------|
| Axis 0 | Down (vertical) | 2 rows |
| Axis 1 | Right (horizontal) | 3 columns |

---

### **For 3D Arrays:**

Shape `(2, 3, 2)` for `a3`:

```
Axis 0: 2 (layers/depth)
Axis 1: 3 (rows per layer)
Axis 2: 2 (columns per row)
```

**Think of it as:**
- Axis 0 = Z (depth, stacking up)
- Axis 1 = Y (height, going down)
- Axis 2 = X (width, going right)

---

### **Remember:**

✓ **Shape** = tuple of sizes: `(size_of_axis0, size_of_axis1, size_of_axis2, ...)`  
✓ **Axes** = These dimensions numbered 0, 1, 2, etc.  
✓ **Always left-to-right**: Index 0 is outermost, last index is innermost

### **Anatomy of a NumPy array**

![Anatomy of a NumPy array](..\assets\images\Anatomy-of-a-Numpy-array.jpg)

In [75]:
# Attributes

a1.shape

(5,)

In [76]:
a2.shape

(2, 3)

In [77]:
a3.shape

(2, 3, 3)

In [78]:
a1

array([1, 2, 3, 4, 5])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
## .ndim -> It tells you how many dimensions an array has

a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [82]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [83]:
# .size -> otal number of elements in an array
# It counts ALL elements regardless of dimensions.

a1.size, a2.size, a3.size

(5, 6, 18)

In [84]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [85]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

# **Create a DataFrame from a Numpy array**

In [86]:
import pandas as pd
import numpy as np

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5
