# **NumPy**

In [1]:
import numpy as np


In [3]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

a3 = np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ***Reshaping and Transposing***

#### **What is Reshape?**
Reshape changes the shape of an array. The data stays the same, but the layout changes. For example, change 6 numbers in a line to 2 rows and 3 columns.

**Why use Reshape?**
- Make arrays same size to do math together
- Get data in right format for models
- Rearrange without losing data

#### **What is Transpose?**
Transpose flips an array. Rows become columns, columns become rows. Use `.T` to do it.

**Why use Transpose?**
- Flip data from rows to columns
- Get data ready for calculations
- Fix array shape when needed

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a3.shape

(2, 3, 3)

In [13]:
# a2 * a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [18]:
# Reshaping

a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [19]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [20]:
a3.shape

(2, 3, 3)

In [21]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [23]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [24]:
# np.newline -> learn difference

In [28]:
a2 , a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [26]:
# Transpose

a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [29]:
a2.T.shape

(3, 2)

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])