# **Numpy**

In [88]:
import pandas as pd
import numpy as np

# ***Creating arrays***

In [89]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [90]:
sample_array.dtype

dtype('int64')

In [91]:
sample_array.shape

(3,)


#### **np.ones()**

In [92]:
# np.ones() = Create an array filled with all 1s

ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [93]:
ones.dtype

dtype('float64')

In [94]:
type(ones)

numpy.ndarray

In [95]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [96]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [97]:
ones = np.ones(5, dtype = int)
ones

array([1, 1, 1, 1, 1])

#### **np.zeros()**

In [98]:
# np.zeros() = Create an array filled with all 0s
# help(np.zeros)

zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [99]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

#### **np.arange()**

In [100]:
# np.arange() = Create a sequence of numbers (like Python's range, but returns an array)
# help(np.arange)

# Start from 0, go to 10, step by 2
range_array = np.arange(0, 10, 2)  # [0 2 4 6 8]
range_array


array([0, 2, 4, 6, 8])

#### **np.random**

> A NumPy tool for generating random numbers

- It's a submodule (a toolbox within NumPy) that creates random data for you.



In [101]:
# creates random floats between 0 and 1.
random_number = np.random.rand()
random_number


# * np.random.random((3, 4)) does exactly the same thing as np.random.rand(3, 4)
# - creates random floats between 0 and 1.

0.4688685990120546

In [102]:
random_array = np.random.random((5, 3))
random_array

array([[0.20029112, 0.69873279, 0.31315353],
       [0.24098928, 0.46671736, 0.14724949],
       [0.06611307, 0.04269692, 0.7593906 ],
       [0.04749349, 0.39988392, 0.52703796],
       [0.86450364, 0.01714188, 0.44931359]])

In [103]:
random_array.shape

(5, 3)

In [104]:
random_array.dtype

dtype('float64')

In [109]:
random_array_2 = np.random.rand(5,3)
random_array_2

array([[0.65391198, 0.50630574, 0.28934256],
       [0.86464486, 0.62067552, 0.03664741],
       [0.52809392, 0.75113788, 0.20295092],
       [0.40295683, 0.27686254, 0.05724427],
       [0.80318093, 0.69259115, 0.63997738]])

In [105]:
# np.random.randint()
# generates random whole numbers (integers) within a range you specify.

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 9, 7, 7, 8],
       [5, 6, 7, 8, 6],
       [6, 3, 0, 2, 8]], dtype=int32)

In [106]:
random_array.size

15

In [107]:
random_array.shape

(3, 5)

In [108]:
random_array = np.random.randint(0, 10)
random_array

2

### ***Pseudo-random numbers***

> np.random.seed()

#### Quick Analogy 💡

**Think of seed() like a recipe:**

- No seed = Chef improvises (different every time)
  
- With seed = Following exact recipe (same dish every time)

## **Similar Functions: Array Creation** 🛠️

### **Quick Reference - All Ways to Create Arrays (Without Lists!)**

| Function | Creates | Use Case | Example |
|----------|---------|----------|---------|
| `np.zeros()` | All **0s** | Initialize empty arrays | `np.zeros((3, 3))` |
| `np.ones()` | All **1s** | Start with baseline values | `np.ones((3, 3))` |
| `np.full()` | All **same value** | Custom initialization | `np.full((3, 3), 7)` |
| `np.arange()` | **Range** of numbers | Sequential data | `np.arange(10)` → 0-9 |
| `np.linspace()` | **Evenly spaced** numbers | Precise ranges | `np.linspace(0, 1, 5)` |

---

### **When to Use Each:**

**`np.zeros()`** ← Start with blank slate
```python
# Reserve space for results you'll fill later
results = np.zeros((100, 10))
```

**`np.ones()`** ← Start with 1s everywhere
```python
# Initialize weights/masks
weights = np.ones((50, 50))
```

**`np.full()`** ← Custom starting value
```python
# Fill with a specific number
matrix = np.full((5, 5), 99)
```

**`np.arange()`** ← Like Python's range() but creates array
```python
# Create sequence 0 to 9
numbers = np.arange(10)
```

**`np.linspace()`** ← Exact number of points
```python
# 5 points evenly from 0 to 1
points = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1.  ]
```

---

### **Pro Tip** 💡

All these functions let you **specify shape** without nested lists:

```python
# ❌ Tedious
big_array = np.array([[0, 0, 0, ...], ...])

# ✅ Clean
big_array = np.zeros((1000, 1000))  # Much easier!
```

---

### **Key Difference: `arange()` vs `linspace()`**

| Function | You specify | Step size |
|----------|------------|-----------|
| `arange(0, 10, 2)` | **Start, stop, step** | You control the step (2) |
| `linspace(0, 10, 5)` | **Start, stop, count** | NumPy calculates the step |

```python
# arange: Step by 2
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# linspace: 5 points from 0 to 10
np.linspace(0, 10, 5)  # [0. , 2.5, 5. , 7.5, 10.]
```