# **Numpy**

In [1]:
import pandas as pd
import numpy as np

# ***Creating arrays***

In [2]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
sample_array.shape

(3,)


#### **np.ones()**

In [5]:
# np.ones() = Create an array filled with all 1s

ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [6]:
ones.dtype

dtype('float64')

In [7]:
type(ones)

numpy.ndarray

In [8]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
ones = np.ones(5, dtype = int)
ones

array([1, 1, 1, 1, 1])

#### **np.zeros()**

In [11]:
# np.zeros() = Create an array filled with all 0s
# help(np.zeros)

zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [12]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

#### **np.arange()**

In [13]:
# np.arange() = Create a sequence of numbers (like Python's range, but returns an array)
# help(np.arange)

# Start from 0, go to 10, step by 2
range_array = np.arange(0, 10, 2)  # [0 2 4 6 8]
range_array


array([0, 2, 4, 6, 8])

#### **np.random**

> A NumPy tool for generating random numbers

- It's a submodule (a toolbox within NumPy) that creates random data for you.



In [14]:
# creates random floats between 0 and 1.
random_number = np.random.rand()
random_number


# * np.random.random((3, 4)) does exactly the same thing as np.random.rand(3, 4)
# - creates random floats between 0 and 1.

0.9630858945001242

In [15]:
random_array = np.random.random((5, 3))
random_array

array([[0.960708  , 0.83686081, 0.60841409],
       [0.79368069, 0.59319168, 0.9204389 ],
       [0.19208451, 0.03044898, 0.38621358],
       [0.62193159, 0.49143426, 0.55457686],
       [0.10562952, 0.82812723, 0.09320433]])

In [16]:
random_array.shape

(5, 3)

In [17]:
random_array.dtype

dtype('float64')

In [18]:
random_array_2 = np.random.rand(5,3)
random_array_2

array([[0.35751231, 0.46088107, 0.94701808],
       [0.0407068 , 0.57656716, 0.215691  ],
       [0.99829923, 0.99935056, 0.53736985],
       [0.54842216, 0.27986885, 0.54069217],
       [0.87072115, 0.66471691, 0.13697562]])

In [19]:
# np.random.randint()
# generates random whole numbers (integers) within a range you specify.

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 3, 4, 5, 2],
       [5, 5, 1, 0, 5],
       [7, 0, 2, 0, 6]], dtype=int32)

In [20]:
random_array.size

15

In [21]:
random_array.shape

(3, 5)

In [22]:
random_array = np.random.randint(0, 10)
random_array

0

## **Similar Functions: Array Creation** 🛠️

### **Quick Reference - All Ways to Create Arrays (Without Lists!)**

| Function | Creates | Use Case | Example |
|----------|---------|----------|---------|
| `np.zeros()` | All **0s** | Initialize empty arrays | `np.zeros((3, 3))` |
| `np.ones()` | All **1s** | Start with baseline values | `np.ones((3, 3))` |
| `np.full()` | All **same value** | Custom initialization | `np.full((3, 3), 7)` |
| `np.arange()` | **Range** of numbers | Sequential data | `np.arange(10)` → 0-9 |
| `np.linspace()` | **Evenly spaced** numbers | Precise ranges | `np.linspace(0, 1, 5)` |

---

### **When to Use Each:**

**`np.zeros()`** ← Start with blank slate
```python
# Reserve space for results you'll fill later
results = np.zeros((100, 10))
```

**`np.ones()`** ← Start with 1s everywhere
```python
# Initialize weights/masks
weights = np.ones((50, 50))
```

**`np.full()`** ← Custom starting value
```python
# Fill with a specific number
matrix = np.full((5, 5), 99)
```

**`np.arange()`** ← Like Python's range() but creates array
```python
# Create sequence 0 to 9
numbers = np.arange(10)
```

**`np.linspace()`** ← Exact number of points
```python
# 5 points evenly from 0 to 1
points = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1.  ]
```

---

### **Pro Tip** 💡

All these functions let you **specify shape** without nested lists:

```python
# ❌ Tedious
big_array = np.array([[0, 0, 0, ...], ...])

# ✅ Clean
big_array = np.zeros((1000, 1000))  # Much easier!
```

---

### **Key Difference: `arange()` vs `linspace()`**

| Function | You specify | Step size |
|----------|------------|-----------|
| `arange(0, 10, 2)` | **Start, stop, step** | You control the step (2) |
| `linspace(0, 10, 5)` | **Start, stop, count** | NumPy calculates the step |

```python
# arange: Step by 2
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# linspace: 5 points from 0 to 10
np.linspace(0, 10, 5)  # [0. , 2.5, 5. , 7.5, 10.]
```

## **Pseudo-random numbers & Seeding** 🎲

### **What is `np.random.seed()`?**

A function that sets the **starting point** for NumPy's random number generator.

---

### **Key Concept: Pseudo-Random Numbers**

Computers can't create truly random numbers - they use a **mathematical formula**:

```
Seed (starting number) → Formula → Chain of "random" numbers
```

**Same seed = Same sequence of "random" numbers**

---

### **What Happens Without a Seed?** ⏰

When you **don't set a seed**, NumPy uses the **current time** (down to microseconds) as the seed:

```python
# No seed provided
np.random.randint(0, 10, size=5)
# Behind the scenes: seed = current time (e.g., 1708185722.456123)
# Output: [3, 7, 2, 9, 1]

# Run again a moment later
np.random.randint(0, 10, size=5)
# Behind the scenes: seed = new time (e.g., 1708185722.789456)
# Output: [5, 8, 4, 1, 6]  ← Different time = different seed!
```

**This creates the illusion of randomness!** 🎭

Since the current time is always changing, you get different numbers each time - making it **appear** truly random (even though it's still following the formula).

---

### **Why Use a Seed?** 🎯

✅ **Reproducibility** - Get same "random" numbers every time  
✅ **Debugging** - Test with consistent data  
✅ **Collaboration** - Share results teammates can reproduce  
✅ **Scientific experiments** - Required for valid research

---

### **Examples**

#### **Without Seed (Different Every Time)**
```python
np.random.randint(0, 10, size=5)
# Run 1: [3, 7, 2, 9, 1]
# Run 2: [5, 8, 4, 1, 6]  ← Different!
# Run 3: [2, 3, 9, 7, 4]  ← Different again!

# Why? Current time keeps changing → different seed each time!
```

#### **With Seed (Same Every Time)**
```python
np.random.seed(42)
np.random.randint(0, 10, size=5)
# Always: [6, 3, 7, 4, 6]

np.random.seed(42)
np.random.randint(0, 10, size=5)
# Always: [6, 3, 7, 4, 6]  ← Identical!

# Why? Seed 42 always starts the formula at the same point!
```

---

### **Best Practices** 💡

```python
# ✅ Set seed ONCE at the top of your notebook
import numpy as np
np.random.seed(42)  # Any number works (42 is popular!)

# Now all random operations are reproducible
data1 = np.random.rand(100)
data2 = np.random.randint(0, 50, size=20)

# ❌ Don't reset seed repeatedly (makes everything identical)
np.random.seed(42)
a = np.random.rand(5)
np.random.seed(42)  # Don't do this!
b = np.random.rand(5)  # Now b = a (not desired!)
```

---

### **Quick Analogy** 🎮

**No Seed** = Valorant match (enemies spawn randomly each round)  
**With Seed** = Practice range (enemies in same spots for practice)

---

### **Common Seed Numbers**

- `42` - Most popular (from "Hitchhiker's Guide to the Galaxy")
- `0` - Simple, common choice
- `123` - Easy to remember
- Any integer works - just pick one and stick with it!

---

### **When to Remove Seed**

```python
# During development/testing: USE seed
np.random.seed(42)
test_data = np.random.rand(100)

# In production/final analysis: REMOVE seed for true randomness
# np.random.seed(42)  ← Comment out
real_data = np.random.rand(100)
```

In [37]:
# Pseudo-random numbers

np.random.seed(42)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [42]:
np.random.seed(42)
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [43]:
random_array_5 = np.random.rand(5,3)
random_array_5

array([[0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [28]:
random_array_4.shape

(5, 3)